({
    baseUrl: "./code/scripts/IUI",
	paths:{
		'jquery': '../jquery',
		'text': '../text',
		'IUI-core':'./IUI-core',
		'IUI':'./IUI',
		'Behaviors':'./core/Behaviors',
		'WidgetBuilder':'./core/WidgetBuilder',
		'View':'./core/View',
		'Template':'./core/Template',
		'Plugable':'./core/Plugable',
		'ObservableModel':'./core/ObservableModel',
		'DataBoundContainer':'./core/DataBoundContainer',
		'OptionModel':'./models/OptionModel',
		'ViewModel':'./models/ViewModel',
		'ContainerModel':'./models/ContainerModel',
		'Widget':'./core/Widget',
		'Utils':'./core/Utils',
		'Validator':'./core/Validator',
		'ContainerUI':'./core/ContainerUI',
		'Overlay':'./core/Overlay',
		'QuickSort':'./utils/QuickSort',
		'Container':'./containers/Container',
		'Viewport':'./containers/Viewport',
		'VerticalScroller':'./containers/VerticalScroller',
		'Row':'./containers/Row',
		'Popover':'./containers/Overlays/Popover',
		'ContextMenu':'./containers/Overlays/ContextMenu',
		'Layout':'./containers/Layout/Layout',
		'Sidebar':'./containers/Layout/Sidebar',
		'Navbar':'./containers/Layout/Navbar',
		'Footer':'./containers/Layout/Footer',
		'ContainerCell':'./containers/ContainerCell',
		'ContainerHeaderCell':'./containers/ContainerHeaderCell',
		'Grid':'./containers/DataBoundContainers/Grid',
		'DataItem':'./core/DataItem',
		'DataMart':'./core/DataMart',
		'InputBox':'./widgets/InputBox',
		'Slider':'./widgets/Slider',
		'Switch':'./widgets/Switch',
		'Button':'./widgets/Button',
		'Division':'./widgets/Division',
		'HeaderCell':'./widgets/HeaderCell',
		'Cell':'./widgets/Cell',
		'ListView':'./widgets/ListView',
		'PageListView':'./widgets/PageListView',
		'ToggleButton':'./widgets/ToggleButton',
		'SubmitButton':'./widgets/SubmitButton',
		'FormLabel':'./widgets/FormLabel',
		'Radio':'./widgets/Radio',
		'NumericInputBox':'./widgets/NumericInputBox',
		'DropDown':'./widgets/DropDown',
		'ComboBox':'./widgets/ComboBox',
		'Exhibit':'./containers/Exhibit',
		'Form':'./containers/Form',
		'RadioGroup':'./containers/RadioGroup'
	},	
	optimize: 'uglify2',
	shim:{
		"IUI": {
			exports: "IUI" 
		}
	},
	name: "IUI",
    out: "./build/IUI.min.js"
})